### ISSUE TITLE
`qaa-qtz` causes issues

### ISSUE THREAD

**Issue by coaxial** [xwmx/iso-639#15]
The list at https://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt has one language row as follows:

```
qaa-qtz|||Reserved for local use|réservée à l'usage local
```

Running `ISO_639.find('qaa-qtz')` returns `nil`. Idem for `'qaa'` or `'qtz'`.

I would expect `ISO_639.find('qaa-qtz')` to return a match instead as it seems to be a valid (albeit irregular) alpha3 code. I don't quite understand what this code is actually used for in practice, but it shouldn't break things.

I believe the bug is here: https://github.com/xwmx/iso-639/blob/master/lib/iso-639.rb#L75. It should be 3 or 7, not just 3.

**Comment by xwmx** [comment]
@coaxial Thanks for the heads up! This should be resolved in the latest version, 0.3.6. Please let me know if you encounter any more issues with this.
