### ISSUE TITLE
Make a case-insensitive method and split on semicolon

### ISSUE THREAD

**Issue by esotericpig** [xwmx/iso-639#7]
Thanks for making this gem. I am using it to parse code from the web that I didn't write. Unfortunately, the data arrives in all caps, like this:

ENGLISH
GERMAN

I could have downcased it and then upcased the first letter, but I made a proper case-insensitive method instead. I know there is the ISO_639.search() method, but I only want it to match if exact.

Also, Spanish is stored as "Spanish; Castilian". Therefore, find_by_english_name("Spanish") will never find it, so I made this method split on the semicolon.

The following will work:
get_lang_entry("ENGLISH")
get_lang_entry("SPANISH")

```
require 'iso-639'

def get_lang_entry(lang)
  lang = lang.gsub(/[[:space:]]+/,'')
  lang = lang.downcase
  
  ISO_639::ISO_639_2.each do |e|
    ls = e.english_name
    ls = ls.split(';')
    
    ls.each do |l|
      l = l.gsub(/[[:space:]]+/,'')
      l = l.downcase
      
      return e if l == lang
    end
  end
    
  return nil
end
```

**Comment by esotericpig** [comment]
Thanks for adding the changes!

**Comment by BenavidesMarc** [comment]
> Thanks for making this gem. I am using it to parse code from the web that I didn't write. Unfortunately, the data arrives in all caps, like this:
> 
> ENGLISH GERMAN
> 
> I could have downcased it and then upcased the first letter, but I made a proper case-insensitive method instead. I know there is the ISO_639.search() method, but I only want it to match if exact.
> 
> Also, Spanish is stored as "Spanish; Castilian". Therefore, find_by_english_name("Spanish") will never find it, so I made this method split on the semicolon.
> 
> The following will work: get_lang_entry("ENGLISH") get_lang_entry("SPANISH")
> 
> ```
> require 'iso-639'
> 
> def get_lang_entry(lang)
>   lang = lang.gsub(/[[:space:]]+/,'')
>   lang = lang.downcase
>   
>   ISO_639::ISO_639_2.each do |e|
>     ls = e.english_name
>     ls = ls.split(';')
>     
>     ls.each do |l|
>       l = l.gsub(/[[:space:]]+/,'')
>       l = l.downcase
>       
>       return e if l == lang
>     end
>   end
>     
>   return nil
> end
> ```
